"""first

Revision ID: 1904441fcd13
Revises: 
Create Date: 2021-04-28 17:19:08.388110

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1904441fcd13'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attitude',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.CheckConstraint('id > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('skill',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=191), nullable=False),
    sa.Column('type', sa.Enum('tech', 'biz', name='skill_types'), nullable=False),
    sa.CheckConstraint('id > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('useraccount',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_type', sa.Enum('Seeker', 'Company', 'Admin', name='account_types'), nullable=False),
    sa.Column('email', sa.String(length=191), nullable=False, comment='login email'),
    sa.Column('password', sa.String(length=191), nullable=False),
    sa.CheckConstraint('id > 0'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('useraccount')
    op.drop_table('skill')
    op.drop_table('attitude')
    # ### end Alembic commands ###
