"""empty message

Revision ID: 85edd8c5d3ef
Revises: 26bceb54a791
Create Date: 2021-04-29 21:06:14.725664

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85edd8c5d3ef'
down_revision = '26bceb54a791'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobpost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('job_title', sa.String(length=191), nullable=False),
    sa.Column('description', sa.String(length=191), nullable=True),
    sa.Column('created_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companyprofile.company_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobpost')
    # ### end Alembic commands ###
